name: tribal_tourism_app
description: "A premium SaaS Flutter app for Tribal Tourism with professional features"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core Dependencies
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Navigation
  go_router: ^14.2.3
  
  # Network & APIs
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  
  # UI & Animations
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  
  # Theme & Design
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1
  
  # Firebase & Backend
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4
  firebase_analytics: ^11.2.1
  
  # Payment Integration
  razorpay_flutter: ^1.3.7
  
  # Local Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  hive_flutter: ^1.1.0
  
  # Media & Camera
  image_picker: ^1.1.2
  video_player: ^2.8.6
  camera: ^0.11.0+1
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  
  # Social Features
  share_plus: ^9.0.0
  
  # Location
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.1.0
  
  # Linting
  flutter_lints: ^4.0.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700